@PostMappingの実装をしました
Masaki-0225/kadai9 pull request #3
Opened 2023-07-11 14:35 UTC by Masaki-0225

# 概要
@PsotMappingを実装し登録処理が可能となりました。

## 動作確認
![登録完了](https://github.com/Masaki-0225/kadai9/assets/134192771/206a1d30-bca3-470d-96c0-84b663a48fc1)

ポストマンを使用し、JSON形式で登録項目を送信します。

### 登録処理後、Getでテーブルを確認する
![Getで取得２](https://github.com/Masaki-0225/kadai9/assets/134192771/d456c997-3401-4560-98be-54adb38c6536)

![Getで取得](https://github.com/Masaki-0225/kadai9/assets/134192771/77c74045-f3c6-48f1-b8fd-016c23b234ea)

mikanさんが新たに登録されています！！

2023-07-11 15:24 UTC, Shibata0806 requested changes
実装お疲れ様です！
とてもいい感じですね！よくがんばりましたね！

Postmanでpostリクエストを投げているスクリーンショットを拝見しましたが、id=5を指定していますが、CreateFormではidは存在しないので、idを指定しても仕方ないかなと思います！

また、バリデーションも入れていただいておりますが、ここもちゃんとバリデーションエラーでメッセージが返ってくるのか、ご確認をよろしくお願いいたします！！

2023-07-11 15:24 UTC, Shibata0806 commented on src/main/java/com/example/kadai9/service/NameServiceImpl.java
> +     return names;
インデントが気になりますね！
InteliJのsave actionで自動的にコードフォーマットできるようにしましょう！

2023-07-11 15:24 UTC, Shibata0806 commented on src/main/java/com/example/kadai9/service/NameServiceImpl.java
> +        Name names = new Name(name ,age);
```suggestion
        Name name = new Name(name ,age);
```
複数形ではなさそうですね！

2023-07-11 15:24 UTC, Shibata0806 commented on src/main/java/com/example/kadai9/mapper/NameMapper.java
> +    @Insert("insert into names (id,name,age) values (#{id},#{name},#{age})")
渡ってくるnameオブジェクトのidって空になりますよね？
テーブル定義的には、auto incrementなので、idはここでは指定しないのが正しい気がしますね！
idなしで一度試してみていただけると嬉しいです！！

2023-07-11 15:24 UTC, Shibata0806 commented on src/main/java/com/example/kadai9/controller/NameController.java
> +        return ResponseEntity.created(url).body("登録完了です");
```suggestion
        return ResponseEntity.created(url)..body(Map.of("message", "Name created successfully"))
```
みたいにして、jsonでレスポンスしてあげると、なお良さそうです！

2023-07-12 14:02 UTC, Masaki-0225 commented on src/main/java/com/example/kadai9/service/NameServiceImpl.java
> +        Name names = new Name(name ,age);
nameだと、下記のようにエラーが出たためnamesしておりました。
![スクリーンショット 2023-07-12 22 16 57](https://github.com/Masaki-0225/kadai9/assets/134192771/7fe03106-466f-4c59-90c3-e377bec23f07)
NameクラスではなくUserクラスにするべきだったかなと思いました。
9747a2ea44e207e3187fef348478016c2404509c

2023-07-12 14:26 UTC, Masaki-0225 commented on src/main/java/com/example/kadai9/mapper/NameMapper.java
> +    @Insert("insert into names (id,name,age) values (#{id},#{name},#{age})")
ご指摘のとおりidはなくても登録処理ができました。
![id無しでも登録できちゃう](https://github.com/Masaki-0225/kadai9/assets/134192771/9c9a4e62-f2d6-4d03-a0b2-8a178e8cc299)
![idなどなかった](https://github.com/Masaki-0225/kadai9/assets/134192771/bd74958f-e064-4637-b590-873ec7c8766a)

2023-07-12 14:30 UTC, Masaki-0225 commented
バリデーションの確認も行いました。
![ヴァリデーション確認](https://github.com/Masaki-0225/kadai9/assets/134192771/bfe67a42-e2d3-4f28-866f-c38a2933c016)
文字数が２０文字を超えるとバッドリクエストが返ってきます。
同様に、ageの部分も１８未満だとバッドリクエストが返ってきました！！

2023-07-13 00:31 UTC, Shibata0806 commented on src/main/java/com/example/kadai9/service/NameServiceImpl.java
> +        Name names = new Name(name ,age);
@Masaki-0225 
なるほどー、変数名が被ってしまってましたか、、、失礼ました。
createnameだと動詞+名詞で変数名みたいになってしまいますので、newNameとかの方が良さそうですね！

`変数 関数 命名規則`とかでググると、一般的にみんながどんな命名をしてるか出てくるので、是非調べてみてください！

2023-07-13 00:42 UTC, Shibata0806 approved these changes

2023-07-13 12:18 UTC, merged